version: "2"
services:
  app:
    container_name: AsyncCrawler
    restart: on-failure
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodb:/data/db/
    ports:
      - "27017:27017"
volumes:
  mongodb: